name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Restore dependencies
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Publish
      run: |
        cd src/TweetPicker.Service
        dotnet publish --no-build -c Release -o ../../out
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
    - name: Push image
      run: |
        docker login -u ${{ DOCKER_USERNAME }} -p ${{ DOCKER_PASSWORD }}
        docker-compose build --no-cache
        docker-compose push
